### ISSUE TITLE
Possible structure of thesis

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/bachelor-thesis#1]
### Part I - Technical Report
- Introduction
  - Motivation
  - Problem description
    - Updateable Vector Tiles
    - Scaling Process for entire planet
    - (Implemention of Mapbox Streets v7)
  - Goals
  - Approach
  - Scope and limitations
- Background
  - Scope of Study Thesis
    - Vector Tiles for Switzerland
    - Workflow for creating vector tiles (not scalable)
- Theorie
  - What are Vector Tiles? (Reference study thesis)
  - TM2Source / Mapnik for Vector Tile creation
  - Imposm3 / PostGIS
- Make Vector Tiles Updatable
  - Approach
    - Search Affected Tiles
    - Calculate Affected Tiles
  - Problems / Optimizations
    - Imposm3 handles Updates as Delete/Insert
    - Imposm3 osm-id vs. Mapbox osm-id
  - Result
- Scaling Vector Tile Workflow for entire planet
  - Approach
    - Devide World in multiple sub-pyramides
    - Render single sub-pyramides on multiple worker nodes
  - Problems / Optimizations
    - Run import just once / mount data partition of database to worker nodes
    - Ignore water tiles
    - Better Locality Effect of tiles using quadtree
  - Result
- (Implementation of Mapbox Streets v7)
  - Approach
    - Adding OSM features based on Streets v7 specification (Imposm3 mapping, source project ect.)
  - Problems / Optimizations
    - Decoupling source project and database schema with zoom level views
    - Optimization with indices on classification functions and pre calculation of heavy topoint-function
    - Result
- Results and Future
### Part II
- Project Management
- Quality Measures
- Project Monitoring
- User / Developer Documentation

**Comment by manuelroth** [comment]
@lukasmartinelli I tried to describe a possible structure of the thesis:
- Introduction - General description of problem/goal/approach
- Background - What was done in study thesis
- Technical Report - The interesting part of the thesis / How were the three main problems solved?
- Results and Future - High-level Results and Future plans with the project
- Appendix - All the boring parts - Need to discuss with Stefan which of these are required/make sense for our thesis

I highly recommend reading [this thesis](http://www.diva-portal.org/smash/get/diva2:851452/FULLTEXT02), the structure is inspired by it. Would love to know what you think about this structure or if you have a completely different idea.

**Comment by lukasmartinelli** [comment]
As discussed with Stefan the structure is ok. But we need to have a part 1 (technical report) and part 2 (where we put the project documentation aka the boring stuff). 

Let's slice the structure up into tasks where we can start to work on.
We can also create milestones again and set ourselves deadlines like last time (for me that helped to get on with writing). Like would be cool to have the thesis finished 1-2 weeks before the final date since we know that the administrative stuff takes a lot of time as well.

I think we can divide the 3 problems quite well into big writing tasks.
I will take over the _Scaling Vector Tile Workflow for entire planet_ part.

> I highly recommend reading this thesis, the structure is inspired by it. Would love to know what you think about this structure or if you have a completely different idea.

Cool stuff learned about Mapbox GL JS and vector tiles. It is pleasent to read and also explains some concepts quite well. Interesting enough there are actually no implementation details or architecture stuff.

**Comment by lukasmartinelli** [comment]
Created the milestones (with deliverables) so we can orient ourselves where we are standing.
https://github.com/osm2vectortiles/bachelor-thesis/milestones

Perhaps there is a better way to structure the goals, just edit and change.
